[package]
name = "phaeton"
version = "0.1.0"
authors = ["morgan"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
osmpbf = "0.1"
