[package]
name = "phaeton"
version = "0.1.0"
authors = ["morgan"]
edition = "2018"

[dependencies]
osmpbf = "0.1"
serde = { version = "1.0", features = ["derive"] }

[lib]
name = "phaeton"
path = "src/lib.rs"

[[bin]]
name = "phaeton"
path = "src/bin.rs"
